use std::sync::Arc;

use anyhow::{Context, Result};
use axum::{
    extract::State,
    http::StatusCode,
    response::{IntoResponse, Json},
    routing::post,
    Router,
};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use tracing::{error, info};

use openclaw_sdk::{AgentConfig, ChatMessage, GroqModel, OpenClawAgent, Task, TaskHandler};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT: &str = "\
You are a legal assistant for Ridge Cell Repair LLC. You provide legal document \
drafts and analysis for review by qualified counsel. IMPORTANT: Always include a \
disclaimer at the end stating that this output is not legal advice and should be \
reviewed by a licensed attorney before use.";

// ---------------------------------------------------------------------------
// Request / response types — contract_review
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct ContractReviewRequest {
    contract_text: String,
    #[serde(default)]
    contract_type: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct RiskItem {
    description: String,
    level: String, // high, medium, low
    clause_reference: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct ContractReviewResult {
    risks: Vec<RiskItem>,
    missing_clauses: Vec<String>,
    unfavorable_terms: Vec<String>,
    recommendations: Vec<String>,
    overall_risk_level: String,
    analysis_timestamp: String,
    disclaimer: String,
}

// ---------------------------------------------------------------------------
// Request / response types — legal_draft
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct LegalDraftRequest {
    document_type: String, // NDA, service_agreement, freelance_contract, terms_of_service, privacy_policy
    parties: Vec<String>,
    #[serde(default)]
    key_terms: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct LegalDraftResult {
    document_type: String,
    document_text: String,
    parties: Vec<String>,
    generated_at: String,
    disclaimer: String,
}

// ---------------------------------------------------------------------------
// Request / response types — compliance_research
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct ComplianceResearchRequest {
    business_type: String,
    jurisdiction: String,
    #[serde(default)]
    specific_questions: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct ComplianceResearchResult {
    business_type: String,
    jurisdiction: String,
    applicable_regulations: Vec<String>,
    required_licenses: Vec<String>,
    compliance_requirements: Vec<String>,
    filing_deadlines: Vec<String>,
    additional_notes: String,
    researched_at: String,
    disclaimer: String,
}

// ---------------------------------------------------------------------------
// Request / response types — dispute_letter
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct DisputeLetterRequest {
    dispute_type: String, // collections, warranty, service, refund
    counterparty: String,
    #[serde(default)]
    amount: Option<f64>,
    issue_description: String,
    desired_resolution: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct DisputeLetterResult {
    letter_text: String,
    suggested_subject_line: String,
    recommended_delivery_method: String,
    generated_at: String,
    disclaimer: String,
}

// ---------------------------------------------------------------------------
// Shared disclaimer
// ---------------------------------------------------------------------------

const DISCLAIMER: &str = "DISCLAIMER: This document was generated by an AI legal \
assistant and does not constitute legal advice. It should be reviewed by a licensed \
attorney before use. Ridge Cell Repair LLC and its agents are not responsible for \
any legal consequences arising from the use of this document without proper legal \
counsel review.";

// ---------------------------------------------------------------------------
// Task implementations
// ---------------------------------------------------------------------------

async fn handle_contract_review(
    agent: &OpenClawAgent,
    soul: &str,
    contract_text: &str,
    contract_type: Option<&str>,
) -> Result<ContractReviewResult> {
    let type_context = match contract_type {
        Some(ct) => format!("This is a {} contract.", ct),
        None => "The contract type is not specified; infer it from the content.".to_string(),
    };

    let prompt = format!(
        r#"Review the following contract and provide a thorough legal analysis.

{type_context}

CONTRACT TEXT:
---
{contract_text}
---

Analyze the contract and respond with a JSON object containing exactly these fields:
{{
  "risks": [
    {{
      "description": "Description of the risk",
      "level": "high|medium|low",
      "clause_reference": "Section or clause number if identifiable, or null"
    }}
  ],
  "missing_clauses": ["List of important clauses that are missing from this contract"],
  "unfavorable_terms": ["List of terms that are unfavorable or one-sided"],
  "recommendations": ["List of specific recommended changes"],
  "overall_risk_level": "high|medium|low"
}}

Be thorough and specific. Reference clause numbers or sections where possible.
Focus on risks relevant to a small business (Ridge Cell Repair LLC).
Respond ONLY with the JSON object, no other text."#
    );

    let messages = vec![
        ChatMessage { role: "system".into(), content: soul.to_string() },
        ChatMessage { role: "user".into(), content: prompt },
    ];
    let response = agent
        .groq()
        .chat(messages, Some(GroqModel::Smart), Some(8192), Some(0.3), true)
        .await
        .context("Groq contract review failed")?;

    let parsed: serde_json::Value =
        serde_json::from_str(&response.text).context("failed to parse LLM JSON response")?;

    let risks: Vec<RiskItem> = serde_json::from_value(
        parsed
            .get("risks")
            .cloned()
            .unwrap_or_else(|| serde_json::json!([])),
    )
    .unwrap_or_default();

    let missing_clauses: Vec<String> = serde_json::from_value(
        parsed
            .get("missing_clauses")
            .cloned()
            .unwrap_or_else(|| serde_json::json!([])),
    )
    .unwrap_or_default();

    let unfavorable_terms: Vec<String> = serde_json::from_value(
        parsed
            .get("unfavorable_terms")
            .cloned()
            .unwrap_or_else(|| serde_json::json!([])),
    )
    .unwrap_or_default();

    let recommendations: Vec<String> = serde_json::from_value(
        parsed
            .get("recommendations")
            .cloned()
            .unwrap_or_else(|| serde_json::json!([])),
    )
    .unwrap_or_default();

    let overall_risk_level = parsed
        .get("overall_risk_level")
        .and_then(|v| v.as_str())
        .unwrap_or("unknown")
        .to_string();

    Ok(ContractReviewResult {
        risks,
        missing_clauses,
        unfavorable_terms,
        recommendations,
        overall_risk_level,
        analysis_timestamp: Utc::now().to_rfc3339(),
        disclaimer: DISCLAIMER.to_string(),
    })
}

async fn handle_legal_draft(
    agent: &OpenClawAgent,
    soul: &str,
    document_type: &str,
    parties: &[String],
    key_terms: &serde_json::Value,
) -> Result<LegalDraftResult> {
    let parties_list = parties
        .iter()
        .enumerate()
        .map(|(i, p)| format!("Party {}: {}", i + 1, p))
        .collect::<Vec<_>>()
        .join("\n");

    let terms_formatted = serde_json::to_string_pretty(key_terms)
        .unwrap_or_else(|_| "{}".to_string());

    let doc_label = match document_type {
        "NDA" => "Non-Disclosure Agreement (NDA)",
        "service_agreement" => "Service Agreement",
        "freelance_contract" => "Freelance Contractor Agreement",
        "terms_of_service" => "Terms of Service",
        "privacy_policy" => "Privacy Policy",
        other => other,
    };

    let prompt = format!(
        r#"Draft a complete {doc_label} in Markdown format.

PARTIES:
{parties_list}

KEY TERMS:
{terms_formatted}

Requirements:
- Use professional legal language appropriate for a small business
- Include all standard sections for this type of document
- Incorporate the key terms provided above into the relevant sections
- Include signature blocks for all parties
- Include an effective date placeholder
- Format the entire document in Markdown with proper headings and numbered sections
- The document should be ready for attorney review and customization

Generate the complete document text. Do not include any preamble or explanation outside the document itself."#
    );

    let response = agent
        .groq()
        .complete(&prompt, Some(GroqModel::Smart), Some(soul), Some(8192), Some(0.3))
        .await
        .context("Groq legal draft generation failed")?;

    Ok(LegalDraftResult {
        document_type: document_type.to_string(),
        document_text: response.text,
        parties: parties.to_vec(),
        generated_at: Utc::now().to_rfc3339(),
        disclaimer: DISCLAIMER.to_string(),
    })
}

async fn handle_compliance_research(
    agent: &OpenClawAgent,
    soul: &str,
    business_type: &str,
    jurisdiction: &str,
    specific_questions: Option<&[String]>,
) -> Result<ComplianceResearchResult> {
    let questions_section = match specific_questions {
        Some(qs) if !qs.is_empty() => {
            let formatted = qs
                .iter()
                .enumerate()
                .map(|(i, q)| format!("{}. {}", i + 1, q))
                .collect::<Vec<_>>()
                .join("\n");
            format!("\nSPECIFIC QUESTIONS TO ADDRESS:\n{formatted}")
        }
        _ => String::new(),
    };

    let prompt = format!(
        r#"Research compliance requirements for the following business:

BUSINESS TYPE: {business_type}
JURISDICTION: {jurisdiction}
{questions_section}

Respond with a JSON object containing exactly these fields:
{{
  "applicable_regulations": ["List of specific laws, regulations, and codes that apply"],
  "required_licenses": ["List of required licenses, permits, and registrations"],
  "compliance_requirements": ["List of ongoing compliance obligations"],
  "filing_deadlines": ["List of important filing deadlines and renewal dates"],
  "additional_notes": "Any additional important considerations or caveats"
}}

Be specific to the jurisdiction and business type. Include regulation names and
code references where possible. Focus on practical, actionable information.
Respond ONLY with the JSON object, no other text."#
    );

    let messages = vec![
        ChatMessage { role: "system".into(), content: soul.to_string() },
        ChatMessage { role: "user".into(), content: prompt },
    ];
    let response = agent
        .groq()
        .chat(messages, Some(GroqModel::Smart), Some(6144), Some(0.4), true)
        .await
        .context("Groq compliance research failed")?;

    let parsed: serde_json::Value =
        serde_json::from_str(&response.text).context("failed to parse LLM JSON response")?;

    let applicable_regulations: Vec<String> = serde_json::from_value(
        parsed
            .get("applicable_regulations")
            .cloned()
            .unwrap_or_else(|| serde_json::json!([])),
    )
    .unwrap_or_default();

    let required_licenses: Vec<String> = serde_json::from_value(
        parsed
            .get("required_licenses")
            .cloned()
            .unwrap_or_else(|| serde_json::json!([])),
    )
    .unwrap_or_default();

    let compliance_requirements: Vec<String> = serde_json::from_value(
        parsed
            .get("compliance_requirements")
            .cloned()
            .unwrap_or_else(|| serde_json::json!([])),
    )
    .unwrap_or_default();

    let filing_deadlines: Vec<String> = serde_json::from_value(
        parsed
            .get("filing_deadlines")
            .cloned()
            .unwrap_or_else(|| serde_json::json!([])),
    )
    .unwrap_or_default();

    let additional_notes = parsed
        .get("additional_notes")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    Ok(ComplianceResearchResult {
        business_type: business_type.to_string(),
        jurisdiction: jurisdiction.to_string(),
        applicable_regulations,
        required_licenses,
        compliance_requirements,
        filing_deadlines,
        additional_notes,
        researched_at: Utc::now().to_rfc3339(),
        disclaimer: DISCLAIMER.to_string(),
    })
}

async fn handle_dispute_letter(
    agent: &OpenClawAgent,
    soul: &str,
    dispute_type: &str,
    counterparty: &str,
    amount: Option<f64>,
    issue_description: &str,
    desired_resolution: &str,
) -> Result<DisputeLetterResult> {
    let amount_text = match amount {
        Some(a) => format!("AMOUNT IN DISPUTE: ${:.2}", a),
        None => "AMOUNT IN DISPUTE: Not specified".to_string(),
    };

    let type_label = match dispute_type {
        "collections" => "Collections Dispute",
        "warranty" => "Warranty Claim",
        "service" => "Service Dispute",
        "refund" => "Refund Request",
        other => other,
    };

    let prompt = format!(
        r#"Generate a professional {type_label} letter.

SENDER: Ridge Cell Repair LLC
RECIPIENT: {counterparty}
{amount_text}

ISSUE DESCRIPTION:
{issue_description}

DESIRED RESOLUTION:
{desired_resolution}

Requirements:
- Professional, firm but not aggressive tone
- Reference relevant consumer protection rights where applicable
- Include a clear timeline for response (typically 30 days)
- Include a statement of next steps if the issue is not resolved
- Format as a proper business letter with date, addresses, salutation, body, and closing
- Sign as "Ridge Cell Repair LLC"

After the letter, also provide:
1. A suggested email subject line
2. The recommended delivery method (e.g., certified mail, email, both)

Respond with a JSON object:
{{
  "letter_text": "The full letter text",
  "suggested_subject_line": "Subject line for email",
  "recommended_delivery_method": "Recommended method"
}}

Respond ONLY with the JSON object, no other text."#
    );

    let messages = vec![
        ChatMessage { role: "system".into(), content: soul.to_string() },
        ChatMessage { role: "user".into(), content: prompt },
    ];
    let response = agent
        .groq()
        .chat(messages, Some(GroqModel::Smart), Some(4096), Some(0.3), true)
        .await
        .context("Groq dispute letter generation failed")?;

    let parsed: serde_json::Value =
        serde_json::from_str(&response.text).context("failed to parse LLM JSON response")?;

    let letter_text = parsed
        .get("letter_text")
        .and_then(|v| v.as_str())
        .unwrap_or("Error: letter text not generated")
        .to_string();

    let suggested_subject_line = parsed
        .get("suggested_subject_line")
        .and_then(|v| v.as_str())
        .unwrap_or("Dispute Notice")
        .to_string();

    let recommended_delivery_method = parsed
        .get("recommended_delivery_method")
        .and_then(|v| v.as_str())
        .unwrap_or("Certified mail with return receipt requested")
        .to_string();

    Ok(DisputeLetterResult {
        letter_text,
        suggested_subject_line,
        recommended_delivery_method,
        generated_at: Utc::now().to_rfc3339(),
        disclaimer: DISCLAIMER.to_string(),
    })
}

// ---------------------------------------------------------------------------
// TaskHandler implementation
// ---------------------------------------------------------------------------

struct LegalHandler {
    soul: String,
}

#[async_trait::async_trait]
impl TaskHandler for LegalHandler {
    async fn handle(&self, agent: &OpenClawAgent, task: &Task) -> Result<serde_json::Value> {
        match task.task_type.as_str() {
            "contract_review" => {
                let contract_text = task
                    .payload
                    .get("contract_text")
                    .and_then(|v| v.as_str())
                    .context("task payload missing 'contract_text' field")?;

                let contract_type = task
                    .payload
                    .get("contract_type")
                    .and_then(|v| v.as_str());

                let result =
                    handle_contract_review(agent, &self.soul, contract_text, contract_type).await?;
                serde_json::to_value(result).context("failed to serialize contract review result")
            }

            "legal_draft" => {
                let document_type = task
                    .payload
                    .get("document_type")
                    .and_then(|v| v.as_str())
                    .context("task payload missing 'document_type' field")?;

                let parties: Vec<String> = task
                    .payload
                    .get("parties")
                    .cloned()
                    .map(serde_json::from_value)
                    .transpose()
                    .context("invalid 'parties' field")?
                    .unwrap_or_default();

                let key_terms = task
                    .payload
                    .get("key_terms")
                    .cloned()
                    .unwrap_or_else(|| serde_json::json!({}));

                let result =
                    handle_legal_draft(agent, &self.soul, document_type, &parties, &key_terms).await?;
                serde_json::to_value(result).context("failed to serialize legal draft result")
            }

            "compliance_research" => {
                let business_type = task
                    .payload
                    .get("business_type")
                    .and_then(|v| v.as_str())
                    .context("task payload missing 'business_type' field")?;

                let jurisdiction = task
                    .payload
                    .get("jurisdiction")
                    .and_then(|v| v.as_str())
                    .context("task payload missing 'jurisdiction' field")?;

                let specific_questions: Option<Vec<String>> = task
                    .payload
                    .get("specific_questions")
                    .cloned()
                    .map(serde_json::from_value)
                    .transpose()
                    .context("invalid 'specific_questions' field")?;

                let qs_ref = specific_questions.as_deref();
                let result =
                    handle_compliance_research(agent, &self.soul, business_type, jurisdiction, qs_ref).await?;
                serde_json::to_value(result)
                    .context("failed to serialize compliance research result")
            }

            "dispute_letter" => {
                let dispute_type = task
                    .payload
                    .get("dispute_type")
                    .and_then(|v| v.as_str())
                    .context("task payload missing 'dispute_type' field")?;

                let counterparty = task
                    .payload
                    .get("counterparty")
                    .and_then(|v| v.as_str())
                    .context("task payload missing 'counterparty' field")?;

                let amount = task
                    .payload
                    .get("amount")
                    .and_then(|v| v.as_f64());

                let issue_description = task
                    .payload
                    .get("issue_description")
                    .and_then(|v| v.as_str())
                    .context("task payload missing 'issue_description' field")?;

                let desired_resolution = task
                    .payload
                    .get("desired_resolution")
                    .and_then(|v| v.as_str())
                    .context("task payload missing 'desired_resolution' field")?;

                let result = handle_dispute_letter(
                    agent,
                    &self.soul,
                    dispute_type,
                    counterparty,
                    amount,
                    issue_description,
                    desired_resolution,
                )
                .await?;
                serde_json::to_value(result)
                    .context("failed to serialize dispute letter result")
            }

            other => {
                anyhow::bail!("unsupported task_type: {}", other);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Shared state for direct API endpoints
// ---------------------------------------------------------------------------

#[derive(Clone)]
struct AppState {
    agent: Arc<OpenClawAgent>,
    soul: String,
}

// ---------------------------------------------------------------------------
// Direct API endpoints
// ---------------------------------------------------------------------------

async fn review_endpoint(
    State(state): State<AppState>,
    Json(req): Json<ContractReviewRequest>,
) -> impl IntoResponse {
    info!("direct API: contract_review");
    match handle_contract_review(&state.agent, &state.soul, &req.contract_text, req.contract_type.as_deref()).await {
        Ok(result) => (
            StatusCode::OK,
            Json(serde_json::to_value(result).unwrap()),
        )
            .into_response(),
        Err(e) => {
            error!(error = %e, "contract review failed");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({ "error": format!("{:#}", e) })),
            )
                .into_response()
        }
    }
}

async fn draft_endpoint(
    State(state): State<AppState>,
    Json(req): Json<LegalDraftRequest>,
) -> impl IntoResponse {
    info!(document_type = %req.document_type, "direct API: legal_draft");
    match handle_legal_draft(&state.agent, &state.soul, &req.document_type, &req.parties, &req.key_terms).await {
        Ok(result) => (
            StatusCode::OK,
            Json(serde_json::to_value(result).unwrap()),
        )
            .into_response(),
        Err(e) => {
            error!(error = %e, "legal draft failed");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({ "error": format!("{:#}", e) })),
            )
                .into_response()
        }
    }
}

async fn compliance_endpoint(
    State(state): State<AppState>,
    Json(req): Json<ComplianceResearchRequest>,
) -> impl IntoResponse {
    info!(
        business_type = %req.business_type,
        jurisdiction = %req.jurisdiction,
        "direct API: compliance_research"
    );
    let qs_ref = req.specific_questions.as_deref();
    match handle_compliance_research(&state.agent, &state.soul, &req.business_type, &req.jurisdiction, qs_ref).await {
        Ok(result) => (
            StatusCode::OK,
            Json(serde_json::to_value(result).unwrap()),
        )
            .into_response(),
        Err(e) => {
            error!(error = %e, "compliance research failed");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({ "error": format!("{:#}", e) })),
            )
                .into_response()
        }
    }
}

async fn dispute_endpoint(
    State(state): State<AppState>,
    Json(req): Json<DisputeLetterRequest>,
) -> impl IntoResponse {
    info!(
        dispute_type = %req.dispute_type,
        counterparty = %req.counterparty,
        "direct API: dispute_letter"
    );
    match handle_dispute_letter(
        &state.agent,
        &state.soul,
        &req.dispute_type,
        &req.counterparty,
        req.amount,
        &req.issue_description,
        &req.desired_resolution,
    )
    .await
    {
        Ok(result) => (
            StatusCode::OK,
            Json(serde_json::to_value(result).unwrap()),
        )
            .into_response(),
        Err(e) => {
            error!(error = %e, "dispute letter failed");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({ "error": format!("{:#}", e) })),
            )
                .into_response()
        }
    }
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let config = AgentConfig::from_env()?;
    let soul = openclaw_sdk::load_soul(&config.agent_id)
        .unwrap_or_else(|| SYSTEM_PROMPT.to_string());
    let agent = OpenClawAgent::new(config);

    let state = AppState {
        agent: Arc::new(agent.clone()),
        soul: soul.clone(),
    };
    let routes = Router::new()
        .route("/review", post(review_endpoint))
        .route("/draft", post(draft_endpoint))
        .route("/compliance", post(compliance_endpoint))
        .route("/dispute", post(dispute_endpoint))
        .with_state(state);

    agent.run(LegalHandler { soul }, routes).await
}
